<a href="https://colab.research.google.com/github/NataMaru/ML_for_people_tasks/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
# Створення матриці matrix
matrix = np.array([[11, 14, 17],
              [20, 23, 26],
              [29, 32, 35]
              ])

# Створення вектора розмірністю 10
vector = np.random.uniform(0, 1, 10)

print("Matrix:", matrix)
print("Matrix shape:", matrix.shape)

print("vector:", vector)
print("vector shape:", vector.shape)

Matrix: [[11 14 17]
 [20 23 26]
 [29 32 35]]
Matrix shape: (3, 3)
vector: [0.52365862 0.84993283 0.69082888 0.12833104 0.1247555  0.82287562
 0.38306866 0.21825026 0.29840723 0.04285387]
vector shape: (10,)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [3]:
#1
vector_vew=(vector+10).round(2)
print("vector:",vector)
print("vector_new:",vector_vew)

vector: [0.52365862 0.84993283 0.69082888 0.12833104 0.1247555  0.82287562
 0.38306866 0.21825026 0.29840723 0.04285387]
vector_new: [10.52 10.85 10.69 10.13 10.12 10.82 10.38 10.22 10.3  10.04]


In [4]:
#2
matrix_new=matrix*2
print("matrix:",matrix)
print("matrix_new:",matrix_new)

matrix: [[11 14 17]
 [20 23 26]
 [29 32 35]]
matrix_new: [[22 28 34]
 [40 46 52]
 [58 64 70]]


In [5]:
#3
vector_squared =vector**2
print("vector:",vector)
print("vector_squared:",vector_squared)

vector: [0.52365862 0.84993283 0.69082888 0.12833104 0.1247555  0.82287562
 0.38306866 0.21825026 0.29840723 0.04285387]
vector_squared: [0.27421835 0.72238582 0.47724455 0.01646886 0.01556394 0.67712429
 0.1467416  0.04763318 0.08904687 0.00183645]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [6]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [7]:
#1
result_matrix =np.dot(  B,A)
display(result_matrix)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [10]:
#2
result_C = np.dot(result_matrix,C)
display(result_C)

array([[0.5202],
       [0.2846]])

In [11]:
#3
result_D=np.dot(result_matrix,D)
display(result_D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [12]:
#1
result_matrix_T=result_matrix.T
display(result_matrix_T)

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [13]:
#2
vector_T=vector.T
display(vector_T)
display(vector)

array([0.52365862, 0.84993283, 0.69082888, 0.12833104, 0.1247555 ,
       0.82287562, 0.38306866, 0.21825026, 0.29840723, 0.04285387])

array([0.52365862, 0.84993283, 0.69082888, 0.12833104, 0.1247555 ,
       0.82287562, 0.38306866, 0.21825026, 0.29840723, 0.04285387])

просте транспонування нічого не змінило. Вектор залишився таким самим як і був, такої ж розмірності

In [14]:
#3
column_vector = np.expand_dims(vector, axis=1)
display(vector)
display(column_vector)

array([0.52365862, 0.84993283, 0.69082888, 0.12833104, 0.1247555 ,
       0.82287562, 0.38306866, 0.21825026, 0.29840723, 0.04285387])

array([[0.52365862],
       [0.84993283],
       [0.69082888],
       [0.12833104],
       [0.1247555 ],
       [0.82287562],
       [0.38306866],
       [0.21825026],
       [0.29840723],
       [0.04285387]])

вектор транспонувася в стовпчик

In [15]:
#4
column_vector_T=column_vector.T
display(column_vector_T)
print(column_vector_T.shape)

array([[0.52365862, 0.84993283, 0.69082888, 0.12833104, 0.1247555 ,
        0.82287562, 0.38306866, 0.21825026, 0.29840723, 0.04285387]])

(1, 10)
